### ISSUE TITLE
phantom throws error when generate diagram

### ISSUE THREAD

**Issue by yapengwu** [akfish/hexo-diagram#1]
Whe I try the example diagram I got the error message from phantom.

   ```
   $ cat source/_posts/Test-Diagram.md
   title: "Test-Diagram"
   date: 2015-05-01 15:38:56
   tags: diagram
   ---
   ### test
   ```sequence
   @found "You", ->
      @message "Think", ->
         @message "Write your idea", "JUMLY", ->
            @create "Diagram"
    jumly.css "background-color":"#8CC84B"
    ```
```

```
hexo s -l

Hexo Diagram Filter
{ diagramFolder: '....hexo/source/diagrams' }
Generate: [sequence]Test-Diagram-diagram-0.png
phantom stdout: ReferenceError: Can't find variable: $

  phantomjs://webpage.evaluate():13
  phantomjs://webpage.evaluate():22
  phantomjs://webpage.evaluate():22

INFO  Hexo is running at http://0.0.0.0:4000/blog/. Press Ctrl+C to stop.
```

**Comment by akfish** [comment]
Fixed in 0.0.10.
